spring:
  application:
    name: agent-timeline

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # PostgreSQL Configuration for Vector Storage
  datasource:
    url: jdbc:postgresql://localhost:5432/agent_timeline
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Web Configuration
  web:
    cors:
      allowed-origins: http://localhost:3000, http://localhost:8080
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"

# Ollama Configuration
ollama:
  base-url: http://localhost:11434
  model: sam860/dolphin3-qwen2.5:3b
  embedding-model: nomic-embed-text
  timeout: 30000

# Phase 5: Context-Augmented Generation Configuration
context:
  # Enable/disable Phase 5 context-augmented generation
  enabled: true
  # Number of chunks to retrieve before each similar chunk
  chunks:
    before: 2
    after: 2
  # Maximum number of similar chunks to retrieve
  max:
    similar: 5
    groups: 3
    total:
      chunks: 20
  # Minimum similarity threshold for chunk retrieval (0.0 to 1.0)
  similarity:
    threshold: 0.3
  # Prompt length management
  prompt:
    max:
      length: 4000
  # Enable truncation for long contexts
  truncation:
    enabled: true

# Logging Configuration
logging:
  level:
    com.agenttimeline: DEBUG
    com.agenttimeline.service.ChunkingService: DEBUG
    com.agenttimeline.service.ContextRetrievalService: DEBUG
    com.agenttimeline.service.EnhancedOllamaService: DEBUG
    com.agenttimeline.service.VectorStoreService: DEBUG
    com.agenttimeline.controller.TimelineController: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /api/v1
