spring:
  application:
    name: agent-timeline

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # PostgreSQL Configuration for Vector Storage
  datasource:
    url: jdbc:postgresql://localhost:5432/agent_timeline
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Web Configuration
  web:
    cors:
      allowed-origins: http://localhost:3000, http://localhost:8080
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"

# Ollama Configuration
ollama:
  base-url: http://localhost:11434
  model: sam860/dolphin3-qwen2.5:3b
  embedding-model: nomic-embed-text
  timeout: 30000

# Phase 6: Enhanced Context Management Configuration
phase6:
  # Enable/disable Phase 6 enhanced context management
  enabled: true

# Conversation History Management
conversation:
  history:
    # Rolling window size (number of recent messages to keep)
    window:
      size: 10
      max-summary-length: 1000
    # History retention settings
    retention:
      max-age-hours: 24
      cleanup-interval-minutes: 60

# Key Information Extraction
extraction:
  # Maximum concurrent extraction requests
  max-concurrent-requests: 5
  # Timeout for extraction requests (seconds)
  timeout-seconds: 30
  # Enable fallback extraction when LLM is unavailable
  enable-fallback: true

# Context Retrieval Configuration (Phase 6 Enhanced)
context:
  retrieval:
    # Retrieval strategy: fixed, adaptive, or intelligent
    strategy: adaptive
    # Chunk retrieval parameters (configurable instead of hardcoded)
    chunks:
      before: 2
      after: 2
      max-per-group: 5
    # Similarity search parameters
    similarity:
      threshold: 0.3
      max-results: 5
    # Adaptive retrieval settings
    adaptive:
      enabled: true
      quality-threshold: 0.7
      expansion-factor: 1.5

# Enhanced Prompt Building
prompt:
  # Maximum prompt length
  max:
    length: 4000
  # Enable intelligent truncation
  truncation:
    enabled: true
  # Context prioritization strategy
  context:
    priority: balanced
  # Include metadata in prompts
  include:
    metadata: true

# Logging Configuration
logging:
  level:
    com.agenttimeline: DEBUG
    com.agenttimeline.service.ChunkingService: DEBUG
    com.agenttimeline.service.ContextRetrievalService: DEBUG
    com.agenttimeline.service.EnhancedOllamaService: DEBUG
    com.agenttimeline.service.VectorStoreService: DEBUG
    com.agenttimeline.controller.TimelineController: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    context-path: /api/v1
